### ISSUE TITLE
TursoClientError: could not parse jwt id

### ISSUE THREAD

**Issue by adriangalilea** [tursodatabase/turso-api-client-ts#17]
When trying
```
const created_db = await turso.databases.create("foo");
```

I get
```
TursoClientError: could not parse jwt id
    at TursoClient.request (webpack-internal:///(rsc)/./node_modules/@tursodatabase/api/dist/index.js:405:13)
```    
 
 I'm using `default` `org` and  the token is the group level one.

**Comment by adriangalilea** [comment]
When I try to do

`const token = await turso.apiTokens.validate("token");`

I get:

```
 ⨯ node_modules/@tursodatabase/api/dist/index.js (398:0) @ eval
 ⨯ Error: Something went wrong! Status 404
    at async createSite (./db/actions.ts:19:19)
    at async Page (testing/page.tsx:17:5)
null
 ⨯ node_modules/@tursodatabase/api/dist/index.js (398:0) @ eval
 ⨯ Error: Something went wrong! Status 404
    at async createSite (./db/actions.ts:19:19)
    at async Page (testing/page.tsx:17:5)
digest: "804469217"
```

**Comment by notrab** [comment]
Hey, the `token` you pass to `createClient` needs to be an API Token you create using the CLI: https://docs.turso.tech/cli/auth/api-tokens/mint

I hope this helps.
